### ISSUE TITLE
Error when use double brace in page content

### ISSUE THREAD

**Issue by fabiocmazzo** [ssddanbrown/BookStack#155] opened 2016-07-27 17:02 UTC
### For Bug Reports
PHP Version:
  5.6+
MySQL Version:
   5.6
Expected Behavior:
   When a page have a double brace in content the page can be edited

Actual Behavior:

   When a page have a double brace in content the page, edit run with error
![page_with_content](https://cloud.githubusercontent.com/assets/3148792/17184466/bdb6c8b6-5402-11e6-94a8-2fcec861e837.png)
![page_with_error](https://cloud.githubusercontent.com/assets/3148792/17184465/bdb6a2e6-5402-11e6-8caa-1d09dceaf7dc.png)

**Comment by ssddanbrown** [comment] 2016-08-05 07:42
May be a duplicate of #150. Will investigate.

**Closed** 2016-08-14 12:10 UTC
Labels: Type: Bug
